import Lean
import Prod
import Example

/-!
# prod-export — entry point

Imports the target module (`Example`), extracts every `@[prod]`-tagged
definition through Lean's own LCNF pipeline (`Prod.Extract`), lowers the
pure-phase declarations to the sexp IR (`Prod.Lower`), and writes:

- `kernel.ir` — the lowered definitions (parsed by Rust `prod-ir`);
- `roots.json` — proof-root metadata (`Prod.Roots`);
- `coverage.md` — per-constant coverage report (`Prod.Coverage`);
- `goldens.ir` — golden values for the kernel defs, computed by running the
  actual compiled Lean definitions on the TF1 instances (same evaluation
  `decide`-checked proofs quantify over). Each golden is a zero-arg def;
  Rust tests assert the generated fns reproduce these values.

Usage: `lake exe prod-export [--out DIR]`. Defaults (cwd = `lean/`):
`../rust/prod-core/kernel.ir`, `../roots.json`, `../coverage.md`,
`../rust/prod-core/goldens.ir`.
-/

open Lean

namespace Prod

/-- Module tree analyzed/exported by this run of prod-export. -/
def targetModule : Name := `Example

/-- Structure type rendered as the IR `Instance` type. -/
def targetInstance : Name := `UorAtlas.Instance

/-- IR module name (kept identical to the legacy fixture for continuity). -/
def targetIrModule : String := "UorAtlas.Kernel"

/-- Assemble the full `kernel.ir` text and per-definition reports. -/
def emitKernelIr (ctx : LowerCtx) (extracted : Array ExtractedDef)
    : CoreM (String × Array DefReport) := do
  let mut ir := s!";; Generated by prod-export (M3): LCNF of {targetModule} → sexp IR.\n(module {targetIrModule}\n"
  let mut reports : Array DefReport := #[]
  for ed in extracted do
    match ed.decl? with
    | some decl =>
      let (sexp, st) ← lowerDecl ctx decl
      let arityNote := if st.dropped == 0 then "" else s!"\n  ;; arity: {st.dropped} erased/type args dropped"
      ir := ir ++ s!"\n  ;; full: {ed.name}{arityNote}\n" ++ indent 2 sexp ++ "\n"
      reports := reports.push
        { name := ed.name, lowered := true, opaques := st.opaques, externs := st.externs }
    | none =>
      reports := reports.push { name := ed.name, lowered := false, skipReason := ed.skipReason }
  return (ir ++ ")\n", reports)

/-- The whole export, as a CoreM computation over the imported environment. -/
def runExport : CoreM (String × String × String) := do
  let env ← getEnv
  let ctx : LowerCtx := {
    instanceType := targetInstance
    tagged := (taggedNames env targetModule).toArray }
  let extracted ← extractTagged targetModule
  let (ir, reports) ← emitKernelIr ctx extracted
  let own := ownConstants env targetModule
  let roots := rootsJson (computeRoots own)
  let coverage ← buildCoverage targetModule own reports
  return (ir, roots, coverage)

/-- `runExport` with exceptions rendered to strings (while CoreM context for
    pretty-printing is still available). -/
def runExportSafe : CoreM (Except String (String × String × String)) := do
  try
    pure (.ok (← runExport))
  catch e =>
    pure (.error (← e.toMessageData.toString))

/-! ## Goldens (M4)

Golden values are computed by *calling the compiled Lean definitions* — the
very functions the theorems quantify over, compiled by the same toolchain —
on the three TF1 instances. Each golden is emitted as a zero-arg sexp `def`
in a second IR module (`goldens.ir`), so Rust can consume it with the same
`prod_defs!` machinery and assert the generated fns reproduce Lean's values.
`classDecode`'s pair value is expressed as nested `(ctor "Prod.mk" ...)`
literal exprs, matching the IR's `Tuple` type. -/

/-- TF1 canonical instance (q=4, T=3, O=8); validity discharged by `decide`. -/
def instCanonical : UorAtlas.Instance := ⟨4, 3, 8, by decide⟩
/-- TF1 demo-small instance (q=2, T=2, O=4). -/
def instDemoSmall : UorAtlas.Instance := ⟨2, 2, 4, by decide⟩
/-- TF1 third instance (q=5, T=1, O=3). -/
def instThird : UorAtlas.Instance := ⟨5, 1, 3, by decide⟩

/-- One golden: a zero-arg def name, its IR return type, and its value body. -/
structure GoldenEntry where
  name : String
  ret : String := "Nat"
  value : String

/-- All goldens: `stride`/`class_count`/`belt` on each TF1 instance, plus
    `classIndex 1 2 3` and `classDecode 43` at the canonical instance. -/
def goldenEntries : Array GoldenEntry := Id.run do
  let mut out := #[]
  for (label, inst) in
      [("canonical", instCanonical), ("demo_small", instDemoSmall), ("third", instThird)] do
    out := out.push { name := s!"golden_stride_{label}", value := toString (UorAtlas.stride inst) }
    out := out.push { name := s!"golden_class_count_{label}", value := toString (UorAtlas.class_count inst) }
    out := out.push { name := s!"golden_belt_{label}", value := toString (UorAtlas.belt inst) }
  let c := instCanonical
  out := out.push { name := "golden_classIndex_1_2_3_canonical", value := toString (UorAtlas.classIndex 1 2 3 c) }
  let (h2, dl) := UorAtlas.classDecode 43 c
  let (d, l) := dl
  out := out.push { name := "golden_classDecode_43_canonical", ret := "(Tuple Nat (Tuple Nat Nat))", value := s!"(ctor \"Prod.mk\" {h2} (ctor \"Prod.mk\" {d} {l}))" }
  return out

/-- Assemble the `goldens.ir` text: one zero-arg def per golden. -/
def emitGoldensIr : String := Id.run do
  let mut ir := s!";; Generated by prod-export (M4): golden values computed by the compiled\n\
    ;; Lean kernel defs on the TF1 instances (canonical/demo_small/third).\n(module UorAtlas.Goldens\n"
  for e in goldenEntries do
    ir := ir ++ s!"\n  (def {e.name} () {e.ret} {e.value})\n"
  return ir ++ ")\n"

end Prod

private def parseOutDir : List String → Option System.FilePath
  | "--out" :: dir :: _ => some dir
  | _ :: rest => parseOutDir rest
  | [] => none

/-- `unsafe` because `Lean.enableInitializersExecution` is an unsafe
    primitive: running imported modules' initializers is required for
    `importModules (loadExts := true)`, which loads env-extension data
    (LCNF `baseExt`, class/instance attribute states) that the simplifier
    needs to unfold instance wrappers (`instHMul`/`instMulNat` chains) to
    kernel calls (`Nat.mul`, ...). -/
unsafe def main (args : List String) : IO Unit := do
  Lean.initSearchPath (← Lean.findSysroot)
  Lean.enableInitializersExecution
  let env ← Lean.importModules #[{ module := Prod.targetModule }] {} (leakEnv := true) (loadExts := true)
  let coreCtx : Core.Context := { fileName := "prod-export", fileMap := default }
  let eio := (ReaderT.run Prod.runExportSafe coreCtx).run { env := env }
  let result ← EIO.toIO' eio
  let (ir, roots, coverage) ← match result with
    | Except.ok (Except.ok outputs, _st) => pure outputs
    | Except.ok (Except.error msg, _st) => throw (IO.userError s!"prod-export failed: {msg}")
    | Except.error _ => throw (IO.userError "prod-export failed: uncaught exception")
  let (irPath, rootsPath, covPath, goldensPath) := match parseOutDir args with
    | some dir =>
      (dir / "kernel.ir", dir / "roots.json", dir / "coverage.md", dir / "goldens.ir")
    | none =>
      ("../rust/prod-core/kernel.ir", "../roots.json", "../coverage.md",
       "../rust/prod-core/goldens.ir")
  IO.FS.writeFile irPath ir
  IO.FS.writeFile rootsPath roots
  IO.FS.writeFile covPath coverage
  IO.FS.writeFile goldensPath Prod.emitGoldensIr
  IO.println s!"prod-export: wrote {irPath}, {rootsPath}, {covPath}, {goldensPath}"
