//! This file is auto-generated by the Lean 4 extraction pipeline.
//! Do not edit by hand. Re-run `lake run rustgen` to regenerate.

#![allow(dead_code)]

use crate::Instance;

/// Auto-generated from Lean 4 UorAtlas.Kernel
pub const fn class_index(h2: u64, d: u64, l: u64, inst: &Instance) -> u64 {
    let stride = inst.t * inst.o;
    stride * h2 + inst.o * d + l
}

pub const fn stride(inst: &Instance) -> u64 {
    inst.t * inst.o
}

pub const fn class_count(inst: &Instance) -> u64 {
    inst.q * stride(inst)
}

pub const fn belt(inst: &Instance) -> u64 {
    class_count(inst) * (1 << (inst.o - 1))
}
