[workspace]
resolver = "2"
members = [
    "prod-ir",
    "prod-codegen",
    "prod-macros",
    "prod-core",
    "prod-cli",
]

[workspace.dependencies]
nom = { version = "7", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
proc-macro2 = "1"
quote = "1"
syn = "2"
clap = { version = "4", features = ["derive"] }
