#check @Nat.mul_succ
#check @Nat.mul_le_mul_left
#check @Nat.mul_pos
#check @Nat.add_mul_div_left
#check @Nat.add_mul_mod_self_left
#check @Nat.div_eq_of_lt
#check @Nat.mod_eq_of_lt
#check @Nat.succ_le_of_lt
#check @Nat.mul_comm
#check @Nat.zero_add
