#![allow(non_snake_case)] // generated names mirror Lean definitions
#![allow(non_camel_case_types)]
// generated enum variants mirror Lean constructors
// Generated bodies are `Ok(expr?)` where a fallible definition's body is one
// expression. That is redundant and `prod-codegen` could emit `expr` instead —
// a real, small improvement, and one nothing could SEE until this crate started
// compiling generated code. It is a codegen change with wide expected-output
// churn, so it does not belong on the PR that introduced the crate; this crate
// judges whether rustc ACCEPTS the output, not whether it is idiomatic.
#![allow(clippy::needless_question_mark)]

//! Makes rustc read the generator's output.
//!
//! # Why this crate exists
//!
//! `prod-codegen`'s unit tests compare generated code as **strings** and never
//! compile it. Every defect that shipped through a green build during the
//! S0/S1 milestone shared that one cause:
//!
//! - a `kernel.ir` whose type declaration said `T`/`O` while its projections
//!   said `t`/`o`, in the same file;
//! - three test fixtures asserting output that mixed both spellings;
//! - a `cases` arity mismatch falling through to a dotted Rust path;
//! - `METHOD_FIELDS` rendering calls to inherent methods that had been deleted;
//! - a fixture asserting a projection of a field its own declaration lacked;
//! - a constructor rendering as `Conformance.NoProp.mk(n, n)`.
//!
//! Six defects, one mechanism. Each emitted Rust that does not compile, at exit
//! 0, past every gate. `syn::parse_str` in `prod-macros` is not a backstop —
//! `A.B.mk(x)` parses fine as a field access followed by a call. Only rustc
//! catches these, and until this crate nothing asked it to.
//!
//! # What it does
//!
//! Expands `prod_defs!` over two IR modules at this crate's root, so the
//! generated code is compiled as ordinary Rust:
//!
//! - **the conformance golden**, which is the real Lean → LCNF → IR pipeline's
//!   output for `lean/Conformance/`. Every future golden bless is now checked
//!   by rustc, not only by eye.
//! - **`fixtures/representative.ir`**, which covers constructs the pipeline
//!   cannot reach yet — above all multi-constructor enums, which `prod-codegen`
//!   implements and unit-tests but which no Lean `inductive` in the corpus
//!   exercises, because every one of them is a single-constructor `structure`.
//!
//! Generated code refers to `crate::ComputeError` and `crate::<TypeName>`, so
//! both invocations must be at the crate root and `ComputeError` must be
//! re-exported here.
//!
//! `tests/smoke.rs` then calls a sample of the generated functions, because
//! compiling proves the shape is valid Rust but not that it computes anything.
//! `tests/rejected.rs` asserts the companion corpus is still rejected.

pub use prod_core::ComputeError;

// The real pipeline's output. Regenerated by `lake exe prod-export`; the
// committed golden is diffed by `just conformance`, and now compiled here.
prod_macros::prod_defs! { ir = "../../lean/Conformance/golden.ir" }

// Hand-written IR for constructs the Lean corpus cannot currently produce.
prod_macros::prod_defs! { ir = "fixtures/representative.ir" }
