//! prod-cli: Command-line tool for parsing Lean 4 IR and generating Rust
//!
//! Usage:
//!   prod parse module.ir
//!   prod gen module.ir [--output generated.rs]
//!   prod validate module.ir

mod roots;

use clap::{Parser, Subcommand};
use std::fs;

#[derive(Parser)]
#[command(name = "prod")]
#[command(about = "Lean 4 → prod IR parser and Rust code generator")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Parse an IR file and print its AST
    Parse {
        /// Path to the IR file
        path: String,
    },
    /// Generate Rust code from an IR file (prints to stdout unless --output is given)
    Gen {
        /// Path to the IR file
        path: String,
        /// Output path for generated Rust code
        #[arg(short, long)]
        output: Option<String>,
    },
    /// Validate an IR file (check for unsupported constructs)
    Validate {
        /// Path to the IR file
        path: String,
    },
    /// Analyze proof roots exported by Lean.
    Roots {
        #[command(subcommand)]
        command: RootCommands,
    },
    /// Render the published Lean-for-production subset contract.
    Subset {
        /// Path to subset.json, written by prod-export
        path: String,
        /// Output path for the rendered markdown
        #[arg(short, long)]
        output: Option<String>,
    },
}

/// The Lean half of the subset contract, written by `prod-export`
/// (`Prod.subsetJson`, `lean/Prod/Emit.lean`).
#[derive(Debug, serde::Deserialize)]
struct SubsetFile {
    operators: Vec<String>,
    conversions: Vec<String>,
    deciders: Vec<String>,
    types: Vec<String>,
}

/// Render the published subset contract: the Lean half (`subset.json`,
/// what `Lower.lean` accepts) merged with the Rust half (`prod_codegen::
/// REJECTIONS`, what `Error` reports). Generated, never hand-written: a
/// hand-maintained contract drifts from the implementation, and a drifted
/// contract is worse than none.
fn render_subset(subset: &SubsetFile) -> String {
    let mut out = String::from(
        "# Lean-for-production: the supported subset\n\n\
         <!-- GENERATED by `just subset`. Do not edit by hand. -->\n\n\
         This is the fragment of Lean 4 that `prod-export` lowers and\n\
         `prod-codegen` renders. Anything outside it is rejected with the\n\
         named error rather than silently mis-compiled.\n\n\
         ## Types\n\n",
    );
    for t in &subset.types {
        out.push_str(&format!("- `{}`\n", t));
    }
    out.push_str(
        "\n**Erased invariants, and where they are re-checked.** A Lean\n\
         structure may carry `Prop` fields expressing invariants over its\n\
         computational fields — for example `UorAtlas.Instance.valid : q ≥ 1 ∧\n\
         T ≥ 1 ∧ O ≥ 1`. `Prop` fields are still erased on export, correctly:\n\
         they are proofs, not data, and carry no runtime representation. What\n\
         happens to the *proposition* depends on whether it falls inside the\n\
         lowerable fragment below. Both outcomes are published, so the first\n\
         thing a reader needs is how to tell which one a given type got.\n\
         \n\
         **Which shape did I get?** Read the generated struct.\n\
         \n\
         - `pub(crate)` fields, plus an `impl` block holding `new` and one\n\
           accessor per field → the invariant **is** enforced.\n\
         - `pub` fields and no `impl` block → the invariant is **not**\n\
           enforced.\n\
         \n\
         There is no third shape and no partially-enforced one: a type\n\
         re-checks its whole proposition or none of it.\n\
         \n\
         **Enforced (the proposition lowered).** The exporter turned it into a\n\
         boolean expression over the structure's own fields, and codegen emits\n\
         a checked constructor — `Instance::new(q, T, O) -> Result<Instance,\n\
         ComputeError>` — that re-checks exactly that proposition and returns\n\
         `ComputeError::InvariantViolated(\"UorAtlas.Instance\")` when it does\n\
         not hold. Outside the crate, `new` is the only way to build the type,\n\
         so the invariant cannot be broken from there. Generated code inside\n\
         the crate does **not** call `new`, by design: Lean already supplied\n\
         the proof, and re-checking would turn proved-total functions\n\
         fallible. That is why the fields are `pub(crate)` rather than\n\
         private.\n\
         \n\
         **Not enforced (the proposition did not lower).** It is dropped. The\n\
         type keeps `pub` fields and gets no constructor and no accessors, and\n\
         the invariant genuinely is not enforced: the struct is a plain data\n\
         carrier, not a refinement type, and a caller that needs the invariant\n\
         must re-check it in Rust by hand.\n\
         \n\
         **The lowerable fragment.** Conjunction (`∧`), disjunction (`∨`),\n\
         negation (`¬`), and the comparisons `=`, `≤`, `<`, `≥`, `>` between a\n\
         field and a literal or between two fields. `≥` and `>` lower to `≤`\n\
         and `<` with their operands swapped, not to nodes of their own.\n\
         Comparisons lower **only on `Nat`, `Int` and the sized kinds**\n\
         (`UInt8`…`UInt64`); `Bool` is deliberately excluded, so a structure\n\
         whose only `Prop` field compares `Bool`s (`flagA = flagB`) gets no\n\
         constructor and takes the unenforced shape. So does anything else\n\
         outside the fragment: quantifiers, arbitrary predicates, `≠` (which\n\
         is `Ne`, not a comparison — spell it `¬ (a = b)` to stay inside), and\n\
         any proposition naming something that is not one of this structure's\n\
         own fields. Falling outside always costs the check, never corrupts\n\
         it.\n",
    );
    out.push_str("\n## Operators\n\n");
    for op in &subset.operators {
        out.push_str(&format!("- `{}`\n", op));
    }
    out.push_str("\n## Conversions\n\n");
    for c in &subset.conversions {
        out.push_str(&format!("- `{}`\n", c));
    }
    out.push_str("\n## Decidable guards\n\n");
    for d in &subset.deciders {
        out.push_str(&format!("- `{}`\n", d));
    }
    out.push_str(
        "\n## Rejections\n\nEverything else fails, precisely:\n\n| Error | Cause |\n|---|---|\n",
    );
    for (variant, cause) in prod_codegen::REJECTIONS {
        out.push_str(&format!("| `{}` | {} |\n", variant, cause));
    }
    out
}

#[derive(Subcommand)]
enum RootCommands {
    /// Check dependency acyclicity and root dependency coverage.
    Check {
        path: String,
        /// Include auto-generated roots (default: hand-written roots only)
        #[arg(long)]
        all: bool,
    },
    /// Print roots on the Pareto front of proof size, kernel depth, and check time.
    Pareto {
        path: String,
        /// Include auto-generated roots (default: hand-written roots only)
        #[arg(long)]
        all: bool,
    },
    /// Generate bridges between roots sharing kernel dependencies.
    Connect {
        path: String,
        root1: Option<String>,
        root2: Option<String>,
        /// Include auto-generated roots (default: hand-written roots only)
        #[arg(long)]
        all: bool,
    },
}

/// Collect every unresolved callee name reachable from an expression.
///
/// The traversal is `prod_ir::Expr::children()`, not a copy of it: this used
/// to hand-match every recursive shape and had already drifted (it never
/// looked inside `Expr::Shr`, added later), so `prod validate` could report a
/// clean bill of health for IR containing an extern call.
fn collect_externs(expr: &prod_ir::Expr, out: &mut Vec<String>) {
    if let prod_ir::Expr::Extern(name, _) = expr {
        out.push(name.clone());
    }
    for child in expr.children() {
        collect_externs(child, out);
    }
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Parse { path } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let (_, module) = prod_ir::parser::parse_module(&content)
                .unwrap_or_else(|e| panic!("Parse error: {:?}", e));
            println!("Module: {}", module.name);
            for def in &module.definitions {
                println!("  Def: {} -> {:?}", def.name, def.ret);
                println!("    Params: {:?}", def.params);
                println!("    Body: {:?}", def.body);
            }
        }
        Commands::Gen { path, output } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let (_, module) = prod_ir::parser::parse_module(&content)
                .unwrap_or_else(|e| panic!("Parse error: {:?}", e));

            let body = prod_codegen::generate_module(&module)
                .unwrap_or_else(|e| panic!("Codegen error: {}", e));

            let mut out = String::from("#![allow(dead_code)]\n\n");
            out.push_str(&format!(
                "// Generated from Lean 4 module: {}\n\n",
                module.name
            ));
            out.push_str(&body);

            match output {
                Some(output) => {
                    fs::write(&output, out)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", output, e));
                    println!("Generated: {}", output);
                }
                None => print!("{}", out),
            }
        }
        Commands::Validate { path } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            match prod_ir::parser::parse_module(&content) {
                Ok((_, module)) => {
                    println!(
                        "✓ Valid IR: {} definitions in module '{}'",
                        module.definitions.len(),
                        module.name
                    );
                    let opaque: Vec<_> = module
                        .definitions
                        .iter()
                        .filter(|d| matches!(d.body, prod_ir::Expr::Opaque(_)))
                        .collect();
                    if !opaque.is_empty() {
                        println!("⚠ {} definitions contain opaque expressions", opaque.len());
                    }
                    let mut unresolved: Vec<String> = Vec::new();
                    for def in &module.definitions {
                        collect_externs(&def.body, &mut unresolved);
                    }
                    unresolved.sort();
                    unresolved.dedup();
                    if !unresolved.is_empty() {
                        println!("✗ {} unresolved call(s):", unresolved.len());
                        for name in &unresolved {
                            println!("    {}", name);
                        }
                        std::process::exit(1);
                    }
                }
                Err(e) => {
                    eprintln!("✗ Invalid IR: {:?}", e);
                    std::process::exit(1);
                }
            }
        }
        Commands::Roots { command } => match command {
            RootCommands::Check { path, all } => {
                let roots = roots::load(&path).unwrap_or_else(|e| panic!("{e}"));
                let roots = roots::filter_roots(roots, all);
                let report = roots::check(&roots);
                println!(
                    "Loaded {} roots{}.",
                    roots.len(),
                    if all {
                        " (including auto-generated)"
                    } else {
                        ""
                    }
                );
                println!(
                    "Checking dependency acyclicity... {}",
                    if report.acyclic { "OK" } else { "FAILED" }
                );
                println!(
                    "Roots with empty dependencies: {}",
                    report.empty_dependencies.len()
                );
                if !report.duplicate_ids.is_empty() {
                    println!(
                        "Warning: duplicate root ids: {}",
                        report.duplicate_ids.join(", ")
                    );
                }
                if report.acyclic && report.empty_dependencies.is_empty() {
                    println!("All root checks passed.");
                } else {
                    std::process::exit(1);
                }
            }
            RootCommands::Pareto { path, all } => {
                let roots = roots::load(&path).unwrap_or_else(|e| panic!("{e}"));
                let roots = roots::filter_roots(roots, all);
                let front = roots::pareto_front(&roots);
                println!("Pareto front: {} roots", front.len());
                for idx in front {
                    let root = &roots[idx];
                    println!(
                        "  {} [{}] (proof_term_size={}, kernel_depth={}, check_time_ns={})",
                        roots::short_name(&root.id),
                        root.id,
                        root.proof_term_size,
                        root.kernel_depth,
                        root.check_time_ns
                    );
                }
            }
            RootCommands::Connect {
                path,
                root1,
                root2,
                all,
            } => {
                let roots = roots::load(&path).unwrap_or_else(|e| panic!("{e}"));
                let roots = roots::filter_roots(roots, all);
                let candidates = roots::bridges(&roots);
                let selected = match (root1, root2) {
                    (Some(a), Some(b)) => candidates
                        .into_iter()
                        .filter(|bridge| {
                            (roots::id_matches(&roots[bridge.left].id, &a)
                                && roots::id_matches(&roots[bridge.right].id, &b))
                                || (roots::id_matches(&roots[bridge.left].id, &b)
                                    && roots::id_matches(&roots[bridge.right].id, &a))
                        })
                        .collect(),
                    (None, None) => candidates,
                    _ => {
                        eprintln!("connect expects either zero or two root ids");
                        std::process::exit(2);
                    }
                };
                for bridge in &selected {
                    let left = roots::short_name(&roots[bridge.left].id);
                    let right = roots::short_name(&roots[bridge.right].id);
                    println!("bridge_{left}_{right}: {left} ↔ {right}");
                    println!("  shared kernel dependencies: {}", bridge.shared.join(", "));
                }
                println!("Generated {} bridge hypotheses.", selected.len());
            }
        },
        Commands::Subset { path, output } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let subset: SubsetFile = serde_json::from_str(&content)
                .unwrap_or_else(|e| panic!("Failed to parse {}: {}", path, e));
            let rendered = render_subset(&subset);
            match output {
                Some(output) => {
                    fs::write(&output, &rendered)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", output, e));
                    println!("Generated: {}", output);
                }
                None => print!("{}", rendered),
            }
        }
    }
}
